server:
  push:
    url: "https://example.com"
    http_headers:
      - key: "Content-Type"
        value: "application/json"
    # Your url params, out: https://example.com?example=true&user_id=3
    url_params:
      - key: "example"
        value: "true"
      - key: "user_id"
        value: "3"
    # default - 5
    send_interval: 5
  pull:
    # Not available

agent:
  # "line_protocol" "json"
  data_type: "json"
  # "push" "pull" (soon)
  send_model: "push"

metrics:
  cpu:
    enabled: true
  memory:
    enabled: true
  system:
    enabled: true
  disks:
    enabled: true
  processes:
    enabled: true
  networks:
    enabled: true
  components:
    enabled: true