[agent]
# Интервал отправки метрик в секундах. Чем меньше - тем больше нагрузка на систему
send_metrics = 5
# "push" or "pull" | INDEV
send_model = "push"
# "line_protocol" or "json"
data_type = "line_protocol"

[server]
key = '''
A unique authorization key for your server.
Can be stored in an environment variable:
export PERSONA_AGENT__SERVER__SERVER_KEY="your_server_key"
'''
token = "your_generated_token"
without_server_key = false
# Куда будут отправляться данные (API сервер или напрямую в дешборд)
# target URL to which metrics will be sent.
# Like the server key, the URL can be written to an environment variable:
# export PERSONA_AGENT__SERVER__SERVER_URL='your_target_url'

url = "http://persona-rs.com/metrics"

[metrics.components]
enabled = true

[metrics.disks]
enabled = true

[metrics.cpu]
enabled = true

[metrics.system]
enabled = true

[metrics.memory]
enabled = true

[metrics.network]
enabled = true