name: Main pipeline

on:
  push:
    branches:
      - develop
      - main

jobs:
  test:
    uses: ./projects/persona-exporter-util/.github/workflows/test.yml

  build:
    if: github.ref_name == 'main'
    needs: test
    uses: ./.github/workflows/build.yml

  release:
    if: github.ref_name == 'main'
    needs: build
    uses: ./.github/workflows/release.yml
