name: Main pipeline

on:
  push:
    branches:
      - develop
      - main

jobs:
  test:
    uses: ./.github/workflows/test.yml

  build:
    if: github.ref_name == 'main'
    needs: test
    uses: ./.github/workflows/build.yml

  release:
    if: github.ref_name == 'main'
    needs: build
    permissions:
      contents: write
    uses: ./.github/workflows/release.yml
