name: Release

on:
  workflow_call:

jobs:
  release:
    runs-on: ubuntu-latest
    environment: persona-exporter
    permissions:
      contents: write
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: persona-exporter*
          merge-multiple: 'true'

      - uses: actions/checkout@v4
      - name: Get version from Cargo.toml
        id: version
        run: |
          VERSION=$(grep -E '^version = ' Cargo.toml | head -n 1 | cut -d '"' -f 2)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Upload
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: persona-exporter*
          generate_release_notes: true
          tag_name: v${{ steps.version.outputs.version }}
          name: Release v${{ steps.version.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}